### ISSUE TITLE
Could the Grow Paddle powerup not remove the Gun powerup?

### ISSUE THREAD

**Issue by TheResplandor** [DusteDdk/SDL-Ball#14]
It seems unintuitive to me that a positive powerup like grow paddle would cancel the Gun, one of the best powerups in the game.
Why was it made that way? Is it just to follow the original game's way, or was it a different decision?

This is obviously not a bug since it was deliberately added in main.cpp line 2322:
```
2319    case PO_GROWPADDLE:
2320                player.coins += 100;
2321                if(p.width < 0.4) p.grow(p.width+0.03);
2322                player.powerup[PO_GUN] = 0;
                    ...
```

**Comment by DusteDdk** [comment]
Thanks for asking, I'm pretty sure I made it that way to put the player in a dilemma, that sometimes, good things happen in a less-than-optimal order, I'd like to keep the mechanic that way.

I'll consider making an exception on easy-mode.
